cleanup formatting and add input checks

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21,17 +21,17 @@
 
 for PKG_NAME in "sbatch" "submitjob.sh" "waitForJobs.sh" "needle" "Rscript" 
 do
-	PKG_PATH=`which $PKG_NAME`
-	if [ -x "$PKG_PATH" ] ; then
-		echo "Found: $PKG_PATH" ;
-	else
-		echo "---------------- CONFIGURATION ERROR ------------------"
-		echo "Configuration failed because $PKG_NAME was not found. "
-		echo "Please make sure it is installed, added to your PATH  "
-		echo "and is executable!"
-		echo "-------------------------------------------------------"
-		exit 1;
-	fi
+  PKG_PATH=`which $PKG_NAME`
+  if [ -x "$PKG_PATH" ] ; then
+    echo "Found: $PKG_PATH" ;
+  else
+    echo "---------------- CONFIGURATION ERROR ------------------"
+    echo "Configuration failed because $PKG_NAME was not found. "
+    echo "Please make sure it is installed, added to your PATH  "
+    echo "and is executable!"
+    echo "-------------------------------------------------------"
+    exit 1;
+  fi
 done
 
 #TODO: Check for R package dependencies
